name: 'Build mod'
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'src/main/resources/assets/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      - name: 'Validate gradle wrapper'
        uses: gradle/wrapper-validation-action@v1
      - name: 'Setup JDK 17'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: 'Make gradle wrapper executable'
        run: chmod +x ./gradlew
      - name: 'Build mod'
        run: ./gradlew build
      - name: 'Get tag'
        id: git_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: 'Draft a new release'
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          name: 'Accurate Block Placement v${{steps.git_tag.outputs.TAG}}'
          body: 'CHANGEME'
          files: 'build/libs/accurate-block-placement-${{steps.git_tag.outputs.TAG}}.jar'
